version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: ai-ci-rabbitmq
    ports:
      - "5672:5672"   # The port the Go app will talk to
      - "15672:15672" # The Web UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
    # The healthcheck tells the Go/Python apps not to start until RabbitMQ is actually ready
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: pgvector/pgvector:pg16
    container_name: ai-ci-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: aidebugger
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  receiver:
    build: 
      context: ./receiver
    container_name: ai_debugger_receiver
    ports:
      - "8080:8080"
    environment:
      # We tell Go to talk to 'rabbitmq' instead of 'localhost'
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - PORT=8080
      - GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}
    depends_on:
      rabbitmq:
        condition: service_healthy

  worker:
    build: 
      context: ./worker
    container_name: ai_debugger_worker
    environment:
      # We tell Python to talk to 'rabbitmq' instead of 'localhost'
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GROQ_API_KEY=${GROQ_API_KEY}
    depends_on:
      rabbitmq:
        condition: service_healthy

# Persistent Storage
volumes:
  rabbitmq_data:
  postgres_data: