name: System Integration CI

on:
  push:
    branches: [ "main", "test-*", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-go-receiver:
    name: Lint & Build Go
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.26'
        
    - name: Go Lint (Vet)
      run: |
        cd receiver
        go vet ./...

    - name: Verify Go Build
      run: |
        cd receiver
        go build -v ./...

  test-python-worker:
    name: Lint & Type-Check Worker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install Analysis Tools
      # We install 'types-requests' and 'types-psycopg2' so Mypy understands our libraries
      run: pip install flake8 mypy types-requests types-psycopg2

    - name: Python Lint (Flake8)
      run: |
        cd worker
        # E9,F63,F7,F82 catch syntax and obvious logic errors
        flake8 main.py --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Static Type Check (Mypy)
      run: |
        cd worker
        # This is what will catch the "0.8" string comparison!
        mypy main.py --ignore-missing-imports

  test-streamlit-dashboard:
    name: Lint & Type-Check Dashboard
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install Analysis Tools
      run: pip install flake8 mypy types-psycopg2

    - name: Dashboard Lint (Flake8)
      run: |
        cd dashboard
        flake8 app.py --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Static Type Check (Mypy)
      run: |
        cd dashboard
        mypy app.py --ignore-missing-imports

  test-docker-infrastructure:
    name: Lint & Build Docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Lint Receiver Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: receiver/Dockerfile

    - name: Lint Dashboard Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: dashboard/Dockerfile

    - name: Verify Docker Compose Syntax
      run: docker compose config

    - name: Test Docker Build
      run: docker compose build